import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/page";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Zahid Showrav",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 0f08fb3272f8b796ae48b6416bb7199d5a599d7f
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-8xl mx-auto ">
          <Sidebar></Sidebar>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </main>
      </body>
    </html>
  );
}
